version: '3'
services:
  scheduleer-mysql:
    image: mysql
    ports:
      - "3307:3306" # HOST:CONTAINER
    environment:
      MYSQL_ROOT_PASSWORD: 9971
      MYSQL_DATABASE: scheduleer
      MYSQL_USER: osk
      MYSQL_PASSWORD: 2090
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/data:/var/lib/mysql
