spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 144445130506-9naf3ggefik9nc9np5t9ku3lahsssmd1.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email