spring:
  config:
    import: classpath:application-app.yml
  mvc:
    hidden-method:
      filter:
        enabled: true

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  freemarker:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        check_nullability: true
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
  kafka:
    bootstrap-servers: localhost:29092

cloud:
  aws:
    stack:
      auto: false
    credentials:
      accessKey: ${ACCESS_KEY}
      secretKey: ${SECRET_KEY}
    region:
      static: ${region}
    s3:
      bucket: ${BUCKET}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**
